### PR TITLE
QUIC 1.1.1r

### PR DESCRIPTION
**Pull request by tmshort**
Rebase onto 1.1.1r

##### Checklist

- [X] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Comment by nibanks** [comment]
Do QUIC stacks need to backport/service this to previous releases (i.e. for security related fixes) or can we just roll new branches forward?

**Comment by richsalz** [comment]
Did this rebase cleanly? If so, approved.  If not, is there a commit to look at?

**Comment by tmshort** [comment]
> Did this rebase cleanly? If so, approved. If not, is there a commit to look at?

Yes, except for the typical conflicts, CHANGES, opensslv.h, etc.

**Comment by tmshort** [comment]
The last commit is new:
[5f7e7de](https://github.com/quictls/openssl/pull/96/commits/5f7e7deff9bced2f824159d8cdcda8b50bb0ebbd)

**Review by richsalz — APPROVED** [review]
...

**Comment by tmshort** [comment]
> Do QUIC stacks need to backport/service this to previous releases (i.e. for security related fixes) or can we just roll new branches forward?

This is based on 1.1.1r, which is a bugfix release. No security issues.

**Review by nibanks — APPROVED** [review]

**Comment by tmshort** [comment]
Upstream is pulling 1.1.1r

**Pull request merged**
