### PR TITLE
OpenSSL 3.0.10+quic rebase

### PR DESCRIPTION
**Pull request by tmshort**
##### Checklist

- [ ] documentation is added or updated
- [ ] tests are added or updated

### CODE REVIEW

**Review by richsalz — APPROVED** [review]

**Comment by wbl** [comment]
The docs failure looks worth fixing, and maybe the ubsan one needs some investigating. I sadly won't have cycles to contribute for a bit.

**Comment by tmshort** [comment]
Yeah, let me add another commit to fix at least the doc issues.

**Comment by tmshort** [comment]
The ubsan/asan issue was due to a bad merge, we lost some `free` calls.

**Comment by tmshort** [comment]
@richsalz @wbl good with the additional changes? CIFuzz and external tests still fail, just as on 3.1.2+quic

**Comment by richsalz** [comment]
Yes, still approved.

**Pull request merged**
