### PR TITLE
Wladd/add quic to openssl 3.1.7

### PR DESCRIPTION
**Pull request by wbl**
Rebase of our QUIC support patches

### CODE REVIEW

**Comment by tmshort** [comment]
I ran the following, and the only conflicts appeared to be due to context (file location) changes:
```
git cherry -v PR-169 openssl-3.1.6+quic openssl-3.1 | grep "^+"
git cherry -v openssl-3.1.6+quic PR-169 openssl-3.1 | grep "^+"
diff <(git show -U0 552e80e3955a101daaf188388514e2b6992622e7) <(git show -U0 402dc4b65969bf55830c9db9d629139883874c19) | less
diff <(git show -U0 2bcaceca0981870185691e596a107d190c10b9de) <(git show -U0 24e9a69e4cc7c8def1af729cf49af9eef52210dc) | less
diff <(git show -U0 8cfc737c0e198393d68efbfbceb0a1bee5b4db18) <(git show -U0 66071c1d753616f2a5d0a567e8e069082461253d) | less
git show  66071c1d753616f2a5d0a567e8e069082461253d
diff <(git show -U0 b34a5ab2bb95590add8e3c04ad857deb11347d0e) <(git show -U0 480cef53b66003dbded07cb9412859a383f4e2b2) | less
diff <(git show -U0 b0832c9104f4e89c6df258662da3177ec41e414b) <(git show -U0 bf43f1e0c1597a5fdc456c284f2766dad27aa3aa) | less
diff <(git show -U0 b0832c9104f4e89c6df258662da3177ec41e414b) <(git show -U0 bf43f1e0c1597a5fdc456c284f2766dad27aa3aa) | less
git show bf43f1e0c1597a5fdc456c284f2766dad27aa3aa
git show fd502648e0464d0811fdd0950e0f1d4f4b3dce49

**Review by tmshort — APPROVED** [review]

**Comment by wbl** [comment]
I don't see failures, just cancellations on the CI, and some checks did go through.

**Comment by wbl** [comment]
The failures so far look ignorable.

**Comment by wbl** [comment]
The FIPS checksums test seems to be less ignorable, but I'm not sure I understand why it fails and the one before it works. It's a test we added, so I'm tempted to drop the commit adding it given we ignored it before.

**Comment by richsalz** [comment]
I think it's fine to drop it.  But we should probably put a point in our README that there are no guarantees that the FIPS module source is identical to what the OpenSSL project got validated, and folks are encouraged to use that FIPS module is they need to

**Comment by wbl** [comment]
I'm afraid I don't understand the test: I don't think it looked at the mainline distro and compared.  I think the diff of the checksum files is still null, so that gives us what we want, but obviously what openssl validates is something different (depends on their version). Their check that their haven't been unnoticed changes is still true.

**Pull request merged**
