### PR TITLE
QUIC 3.0.6

### PR DESCRIPTION
**Pull request by tmshort**
Rebase onto 3.0.6

##### Checklist

- [X] documentation is added or updated
- [X] tests are added or updated

### CODE REVIEW

**Comment by tmshort** [comment]
Not worried about the `CIFuzz/Fuzzing`, it's a build issue in a file not touched by QUIC

**Comment by richsalz** [comment]
Did it rebase cleanly?  If so, approved.  If not, what commit should I look at?

**Comment by tmshort** [comment]
> Did it rebase cleanly? If so, approved. If not, what commit should I look at?

Yes, except for the typical ones: i.e. VERSION.dat, README.md.

**Comment by tmshort** [comment]
The last two commits are new: 
[fe56fe8](https://github.com/quictls/openssl/pull/97/commits/fe56fe891f7825f9da80c8c787cea1945dc67ec8)
[107dffe](https://github.com/quictls/openssl/pull/97/commits/107dffea38b737fc8f5124cfca467376d08a8988)

**Review by richsalz — APPROVED** [review]
fine by me.

**Comment by tmshort** [comment]
Upstream is pulling 3.0.6.

**Pull request merged**
