### PR TITLE
Openssl 3.0.14+quic

### PR DESCRIPTION
**Pull request by xl32**
Openssl 3.0.14+quic with several CVEs fixed

There is no 3.0.14 branch in your repo, so I selected 3.0.13 as a base.

### CODE REVIEW

**Comment by kaduk** [comment]
@xl32  I created the appropriate branch for the merge base and updated the PR to match.

**Comment by eilandert** [comment]
> @xl32 I created the appropriate branch for the merge base and updated the PR to match.

Ping! ;-)  Can someone approve this so we can get a release?

**Comment by rapsys** [comment]
:+1:

**Comment by rapsys** [comment]
Thx for your hard work everyone.

May we get this release or know if the xl32 merge branch is safe to include in linux distribution ?

Best regards

**Comment by eilandert** [comment]
> Thx for your hard work everyone.
> 
> May we get this release or know if the xl32 merge branch is safe to include in linux distribution ?
> 
> Best regards

I created debian/ubuntu packages from the xl32 merge branch, no problems so far. You can get them at https://deb.myguard.nl/pool/main/o/openssl/ if you want to test

**Comment by rapsys** [comment]
> I created debian/ubuntu packages from the xl32 merge branch, no problems so far.
> You can get them at https://deb.myguard.nl/pool/main/o/openssl/ if you want to test.
I did the package for a distribution I am contributor in, I fear to include unreviewed code as update...
I really hope we will get this official release soon.

**Review by tmshort — APPROVED** [review]
I did the `git cherry` comparison, and this looks fine.

**Comment by richsalz** [comment]
Thanks @tmshort   For the benefit of some of us, what's the cherry-pick comparison?

**Pull request merged**
